export const products = [
  {
    id: "1",
    title: "Producto 1",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 1",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "2",
    title: "Producto 2",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 1",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "3",
    title: "Producto 3",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 1",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "4",
    title: "Producto 4",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 1",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "5",
    title: "Producto 5",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 2",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "6",
    title: "Producto 6",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 2",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "7",
    title: "Producto 7",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 2",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "8",
    title: "Producto 8",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 2",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "9",
    title: "Producto 9",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 3",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "10",
    title: "Producto 10",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 3",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "11",
    title: "Producto 11",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 3",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
  {
    id: "12",
    title: "Producto 12",
    price: 1000,
    stock: 20,
    description: "Producto generico",
    category: "Categoría 3",
    imageUrl: "https://istore.gt/wp-content/uploads/2023/02/ART004467i-1.jpg",
  },
];
